<?php $__env->startSection('title', 'Sales Management'); ?>
<?php $__env->startSection('content'); ?>
<div class="top"><div><h1>Sales Management</h1><div class="muted">View completed sales and manage delivery orders that are still pending.</div></div><div class="who"><?php echo e(auth()->user()->role === 'OWNER' ? 'Owner' : 'Sales Clerk'); ?></div></div>

<form method="GET" action="<?php echo e(route('sales.index')); ?>" class="toolbar" style="justify-content:space-between;align-items:center;flex-wrap:wrap">
    <div style="display:flex;gap:8px;flex-wrap:wrap;flex:1"><input class="input" style="max-width:260px" name="q" value="<?php echo e(request('q')); ?>" placeholder="Search sale reference or user..."><select name="status" style="max-width:190px"><option value="">All Status</option><option value="PENDING" <?php if(request('status')==='PENDING'): echo 'selected'; endif; ?>>Pending Delivery</option><option value="COMPLETED" <?php if(request('status')==='COMPLETED'): echo 'selected'; endif; ?>>Completed</option><option value="CANCELLED" <?php if(request('status')==='CANCELLED'): echo 'selected'; endif; ?>>Cancelled Delivery</option></select><button class="btn primary">Filter</button><?php if(request()->hasAny(['q','status'])): ?><a class="btn light" href="<?php echo e(route('sales.index')); ?>">Clear</a><?php endif; ?></div>
    <a class="btn primary" href="<?php echo e(route('sales.create')); ?>">+ New Sale</a>
</form>

<div class="card" style="padding:0;overflow:hidden"><div style="overflow-x:auto"><table class="table"><thead><tr><th>Reference</th><th>Date / Time</th><th>Items</th><th>Total Amount</th><th>Delivery</th><th>Status</th><th>Recorded By</th><th>Action</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $sales; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $sale): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong>SALE-<?php echo e(str_pad($sale->sale_id,4,'0',STR_PAD_LEFT)); ?></strong></td><td><?php echo e($sale->sale_date->format('m/d/Y g:i A')); ?></td><td><?php echo e($sale->items->count()); ?></td><td>₱<?php echo e(number_format((float)$sale->total_amount,2)); ?></td><td><?php echo e($sale->delivery_required?'Required':'No'); ?></td><td><?php if($sale->status==='PENDING'): ?><span class="sale-status pending">Pending Delivery</span><?php elseif($sale->status==='CANCELLED'): ?><span class="sale-status cancelled">Cancelled Delivery</span><?php else: ?><span class="sale-status completed">Completed</span><?php endif; ?></td><td><?php echo e($sale->user?->username??'—'); ?></td><td><?php if($sale->delivery_required && $sale->status==='PENDING'): ?><div style="display:flex;gap:6px;flex-wrap:wrap"><form method="POST" action="<?php echo e(route('sales.complete-delivery',$sale)); ?>" onsubmit="return confirm('Confirm that the customer successfully received this delivery?')"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn success small">Complete</button></form><form method="POST" action="<?php echo e(route('sales.cancel-delivery',$sale)); ?>" onsubmit="return confirm('Cancel this delivery? Reserved stock will be returned to inventory.')"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn danger small">Cancel Delivery</button></form></div><?php else: ?><span class="muted">—</span><?php endif; ?></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="8" class="muted" style="text-align:center;padding:30px">No sales transactions recorded yet.</td></tr><?php endif; ?>
</tbody></table></div></div>
<?php if($sales->hasPages()): ?><div style="display:flex;justify-content:center;align-items:center;gap:12px;margin-top:18px"><a class="btn light small <?php echo e($sales->onFirstPage()?'disabled-link':''); ?>" href="<?php echo e($sales->previousPageUrl()?:'#'); ?>">‹ Previous</a><span class="muted">Page <?php echo e($sales->currentPage()); ?> of <?php echo e($sales->lastPage()); ?></span><a class="btn light small <?php echo e($sales->hasMorePages()?'':'disabled-link'); ?>" href="<?php echo e($sales->nextPageUrl()?:'#'); ?>">Next ›</a></div><?php endif; ?>
<style>.sale-status{display:inline-block;padding:6px 9px;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.sale-status.pending{background:#fff3cd;color:#9a6700}.sale-status.completed{background:#dff7e9;color:#08783d}.sale-status.cancelled{background:#fde2e4;color:#b4232d}.disabled-link{pointer-events:none;opacity:.45}</style>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Projects\IT12_project\resources\views/sales/index.blade.php ENDPATH**/ ?>