@extends('layouts.app')
@section('title', 'Sales Management')
@section('content')
<div class="top"><div><h1>Sales Management</h1><div class="muted">View completed sales and manage delivery orders that are still pending.</div></div><div class="who">{{ auth()->user()->role === 'OWNER' ? 'Owner' : 'Sales Clerk' }}</div></div>

<form method="GET" action="{{ route('sales.index') }}" class="toolbar" style="justify-content:space-between;align-items:center;flex-wrap:wrap">
    <div style="display:flex;gap:8px;flex-wrap:wrap;flex:1"><input class="input" style="max-width:260px" name="q" value="{{request('q')}}" placeholder="Search sale reference or user..."><select name="status" style="max-width:190px"><option value="">All Status</option><option value="PENDING" @selected(request('status')==='PENDING')>Pending Delivery</option><option value="COMPLETED" @selected(request('status')==='COMPLETED')>Completed</option><option value="CANCELLED" @selected(request('status')==='CANCELLED')>Cancelled Delivery</option></select><button class="btn primary">Filter</button>@if(request()->hasAny(['q','status']))<a class="btn light" href="{{route('sales.index')}}">Clear</a>@endif</div>
    <a class="btn primary" href="{{ route('sales.create') }}">+ New Sale</a>
</form>

<div class="card" style="padding:0;overflow:hidden"><div style="overflow-x:auto"><table class="table"><thead><tr><th>Reference</th><th>Date / Time</th><th>Items</th><th>Total Amount</th><th>Delivery</th><th>Status</th><th>Recorded By</th><th>Action</th></tr></thead><tbody>
@forelse($sales as $sale)<tr><td><strong>SALE-{{str_pad($sale->sale_id,4,'0',STR_PAD_LEFT)}}</strong></td><td>{{$sale->sale_date->format('m/d/Y g:i A')}}</td><td>{{$sale->items->count()}}</td><td>₱{{number_format((float)$sale->total_amount,2)}}</td><td>{{$sale->delivery_required?'Required':'No'}}</td><td>@if($sale->status==='PENDING')<span class="sale-status pending">Pending Delivery</span>@elseif($sale->status==='CANCELLED')<span class="sale-status cancelled">Cancelled Delivery</span>@else<span class="sale-status completed">Completed</span>@endif</td><td>{{$sale->user?->username??'—'}}</td><td>@if($sale->delivery_required && $sale->status==='PENDING')<div style="display:flex;gap:6px;flex-wrap:wrap"><form method="POST" action="{{route('sales.complete-delivery',$sale)}}" onsubmit="return confirm('Confirm that the customer successfully received this delivery?')">@csrf @method('PATCH')<button class="btn success small">Complete</button></form><form method="POST" action="{{route('sales.cancel-delivery',$sale)}}" onsubmit="return confirm('Cancel this delivery? Reserved stock will be returned to inventory.')">@csrf @method('PATCH')<button class="btn danger small">Cancel Delivery</button></form></div>@else<span class="muted">—</span>@endif</td></tr>
@empty<tr><td colspan="8" class="muted" style="text-align:center;padding:30px">No sales transactions recorded yet.</td></tr>@endforelse
</tbody></table></div></div>
@if($sales->hasPages())<div style="display:flex;justify-content:center;align-items:center;gap:12px;margin-top:18px"><a class="btn light small {{$sales->onFirstPage()?'disabled-link':''}}" href="{{$sales->previousPageUrl()?:'#'}}">‹ Previous</a><span class="muted">Page {{$sales->currentPage()}} of {{$sales->lastPage()}}</span><a class="btn light small {{$sales->hasMorePages()?'':'disabled-link'}}" href="{{$sales->nextPageUrl()?:'#'}}">Next ›</a></div>@endif
<style>.sale-status{display:inline-block;padding:6px 9px;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.sale-status.pending{background:#fff3cd;color:#9a6700}.sale-status.completed{background:#dff7e9;color:#08783d}.sale-status.cancelled{background:#fde2e4;color:#b4232d}.disabled-link{pointer-events:none;opacity:.45}</style>
@endsection
